apiVersion: v1
kind: Service
metadata:
    name: invoiceappdb-service
spec:
    selector:
        app: invoiceappdb
    ports:
        - protocol: TCP
          port: 1433
          targetPort: 1433
    type: LoadBalancer